### PR TITLE
beam search

### PR DESCRIPTION
**Pull request by sunxiaobiu**
use beam search to select the best suitable sample

### CODE REVIEW

**Comment by hunkim** [comment]
Do you have example outputs from the beam search? Are results better?

Rather than removing the weighted, should we have an option for the beam search?

**Comment by sunxiaobiu** [comment]
sorry for the late reply，I think beam search can be used to predict the following words, or even create the following words, predict, filter the maximum probability of the words, feed back, continue to predict ...
1.	with weighted select code we can only predict one letter at a time, but this is greedy
2.	We can also predict more than a word  at a time, and then pick the higher probability of the overall , in order to reduce the impact of accidental factors
3.	when we predict more than a word, only a relatively high probability of several candidates to do the prediction, that's beam search. 
4.	However, using beam search has the disadvantage that the generated sequence grows exponentially

btw I only removed the weighted, and take the beam search as a replacement. I think to achieve better result , we need to add beam embedding method to select multi-character
in the step of word embedding. I need extra time to put the idea into practice and use some examples to test the results.

**Comment by hunkim** [comment]
Still, I don't want to kill the current 'weighted_pick'. Can you make beam_search as a sampling option?

Also, what would be the output using your beam search? Could you provide some example outputs? Do you think it's better?

**Comment by normanheckscher** [comment]
I've created a new branch and integrated this beam search into the sample code as an option. Advise on how well it works or doesn't work and if it's appropriate the branch can be merged into the master.

**Comment by hunkim** [comment]
Thanks! Could you make it as another PR so that we can see the diff easily?

One issue is checking the performance. Do you have any idea how to check if this beam search is a right/good implementation.

Cheers!

**Comment by normanheckscher** [comment]
I'll close this PR as the code in the new PR mirrors this code.

**Pull request closed without merging**
